### ISSUE TITLE
Sunday Issue for DayOfTheWeek 

### ISSUE THREAD

**Issue by krishna-koushik** [waneka/cron-builder#14]
Hi,

I was investigating cron-builder and wanted to use it in my code but the problem i am now running into is that we need the value of sunday to be 0 instead of 7.

**Comment by krishna-koushik** [comment]
Created a pull request to fix address this issue. https://github.com/sourceclear/cron-builder/pull/15

**Comment by sbimochan** [comment]
This is not in release
