### ISSUE TITLE
The week day values should vary between 0 and 6 as per the standard cron string.

### ISSUE THREAD

**Issue by rajeshwar-fissionlabs** [waneka/cron-builder#17]
this PR has merged but this is wrong.
https://github.com/sourceclear/cron-builder/pull/15

**Comment by waneka** [comment]
@rajeshwar-fissionhq there is some debate about whether or not `7` is a valid value for weekdays. In the readme, I reference [this article](https://en.wikipedia.org/wiki/Cron) as the source of truth for the project, and it states that 7 is a valid value.

More importantly, I don't think that adding 7 as an acceptable value for Sunday will have a negative effect. Is this negatively effecting you in any way?

**Comment by rajeshwar-fissionlabs** [comment]
No, but value 7 is not standard value for sunday.

**Comment by waneka** [comment]
Since there are some users that may consider 7 valid as an optional value for Sunday, and it won't negatively effect users that don't, I'm going to leave the PR merged and close this issue. Thanks for bringing it to my attention.
